### PR TITLE
Add talk for tomorrow

### PR DESCRIPTION
**Pull request by matthiasbeyer**
@neithernut @manuelmessner @asuivelentine @hfuunfug/members 

Any complains about a talk tomorrow? If not, I will merge and republish the site and also enter this talk in the official IPFS event calendar (if possible).

### CODE REVIEW

**Comment by asuivelentine** [comment]
yeeep, sounds nice. With dinner afterwards

**Comment by matthiasbeyer** [comment]
More like with dinner during the session, because I'm not planning a normal talk but rather a get-together with a bit hands-on!

**Comment by asuivelentine** [comment]
Yeah sounds even better. should we change the location to C2.16 temporary

**Comment by matthiasbeyer** [comment]
@asuivelentine please ACK the update after a review, will republish in ~30 mins then.

**Comment by asuivelentine** [comment]
ack

**Comment by matthiasbeyer** [comment]
Republished. Later than expected, but anyways...

**Pull request merged**
