### PR TITLE
Add metadata show

### LINKED ISSUE #25: Add meta data for entry details
When viewing an article in detail, information previously shown on home page (date, author, title) are not shown any more.

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Closes #25

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
@fkemmer I hope this is what you suggested?

**Comment by fkemmer** [comment]
basically yes. However, you seem to have mixed German and English (which, digging a bit further seems to be a general problem of the page):

```
Titel: A new unfug.org website
Datum: 2015-06-20
Speaker(s): Matthias Beyer
```

**Comment by matthiasbeyer** [comment]
~~Ah, of course. Have to rework this whole thing, yes.~~

Fixed

**Comment by fkemmer** [comment]
looks good now

**Pull request merged**
