### PR TITLE
Fix wording in ups

### PR DESCRIPTION
**Pull request by TheNeikos**

### CODE REVIEW

**Comment by TheNeikos** [comment]
@matthiasbeyer @hfuunfug/members

**Comment by matthiasbeyer** [comment]
Did you test-build the site?

**Comment by TheNeikos** [comment]
No, since I only changed text :?

**Comment by matthiasbeyer** [comment]
You also changed the header and I'm not sure this compiles down to what you expect. I will build this locally as soon as I have time and then propose fixes or merge.

**Comment by matthiasbeyer** [comment]
Deployed.

**Comment by TheNeikos** [comment]
:dancer:

**Pull request merged**
